"""Add stripe_customer_id to User model

Revision ID: 1010ce590f99
Revises: 76e4bde46c42
Create Date: 2025-01-08 00:06:48.187391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1010ce590f99'
down_revision = '76e4bde46c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
