"""Added REVOKED status to ProjectStatus enum

Revision ID: 1d41e823d32d
Revises: 92747833e318
Create Date: 2025-02-20 21:21:53.435725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d41e823d32d'
down_revision = '92747833e318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_index('ix_notifications_user_id')

    # def upgrade():
    op.execute("ALTER TABLE projects MODIFY COLUMN status ENUM('DRAFT', 'PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'SUCCESSFUL', 'CANCELLED', 'FAILED', 'REVOKED') NOT NULL;")

    # ### end Alembic commands ###


def downgrade():
    # def downgrade():
    op.execute("ALTER TABLE projects MODIFY COLUMN status ENUM('DRAFT', 'PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'SUCCESSFUL', 'CANCELLED', 'FAILED') NOT NULL;")
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
