"""changes the amount in float to numeric

Revision ID: 27bfbc7b4921
Revises: 1d41e823d32d
Create Date: 2025-02-22 11:31:54.229797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27bfbc7b4921'
down_revision = '1d41e823d32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_index('ix_notifications_user_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'SUCCESSFUL', 'CANCELLED', 'FAILED', 'REVOKED'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'SUCCESSFUL', 'CANCELLED', 'FAILED', 'REVOKED'),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
