"""Add backers_count to Project model

Revision ID: 31ce9e39f07b
Revises: 27bfbc7b4921
Create Date: 2025-02-24 17:47:26.109402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ce9e39f07b'
down_revision = '27bfbc7b4921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_index('ix_notifications_user_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backers_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('backers_count')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
