"""Update reward model with new fields

Revision ID: 39fa40510dc0
Revises: aab9ed4c700f
Create Date: 2024-11-03 15:18:45.821313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39fa40510dc0'
down_revision = 'aab9ed4c700f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fee_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('refund_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_country', sa.String(length=2), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PROCESSING', 'CANCELLED', 'DECLINED', 'DISPUTED'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.alter_column('method',
               existing_type=mysql.ENUM('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CRYPTO', 'MOBILE_PAYMENT', 'WALLET'),
               nullable=False,
               existing_server_default=sa.text("'CREDIT_CARD'"))
        batch_op.alter_column('provider',
               existing_type=mysql.ENUM('STRIPE', 'PAYPAL', 'SQUARE', 'RAZORPAY', 'FLUTTERWAVE'),
               nullable=False,
               existing_server_default=sa.text("'STRIPE'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index('idx_donation_id', ['donation_id'], unique=False)
        batch_op.create_index('idx_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_status_created_at')
        batch_op.drop_index('idx_donation_id')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('provider',
               existing_type=mysql.ENUM('STRIPE', 'PAYPAL', 'SQUARE', 'RAZORPAY', 'FLUTTERWAVE'),
               nullable=True,
               existing_server_default=sa.text("'STRIPE'"))
        batch_op.alter_column('method',
               existing_type=mysql.ENUM('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CRYPTO', 'MOBILE_PAYMENT', 'WALLET'),
               nullable=True,
               existing_server_default=sa.text("'CREDIT_CARD'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PROCESSING', 'CANCELLED', 'DECLINED', 'DISPUTED'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.drop_column('ip_country')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('fee_amount')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
