"""Add description to Permission model

Revision ID: 69ec50ccc794
Revises: 443bd5e6c2ad
Create Date: 2024-10-10 00:49:04.829759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ec50ccc794'
down_revision = '443bd5e6c2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
