"""Added a currency to the project model

Revision ID: 75026ece0658
Revises: f04194bf0584
Create Date: 2025-02-28 20:10:34.390160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75026ece0658'
down_revision = 'f04194bf0584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_index('ix_notifications_user_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
