"""2fa implementation and email_services

Revision ID: 75985e0c1f8d
Revises: 69ec50ccc794
Create Date: 2024-10-10 15:28:16.021057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75985e0c1f8d'
down_revision = '69ec50ccc794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_setup_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_setup_code')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('two_factor_secret')

    # ### end Alembic commands ###
