# """Regenerate migration script for notifications table

# Revision ID: 86f24fddc5e5
# Revises: b55e2dd4efeb
# Create Date: 2025-01-08 02:34:05.855979

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = '86f24fddc5e5'
# down_revision = 'b55e2dd4efeb'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('notifications', schema=None) as batch_op:
#         # batch_op.drop_index('ix_notifications_user_id')  # Commented out

#     # ### end Alembic commands ###

# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('notifications', schema=None) as batch_op:
#         # batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)  # Commented out

#     # ### end Alembic commands ###
"""Regenerate migration script for notifications table

Revision ID: 86f24fddc5e5
Revises: b55e2dd4efeb
Create Date: 2025-01-08 02:34:05.855979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f24fddc5e5'
down_revision = 'b55e2dd4efeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # Placeholder for an empty function
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # Placeholder for an empty function
    # ### end Alembic commands ###
