"""Specify foreign key for Donation.reward

Revision ID: 95bfe20087ce
Revises: f6f74ec74b82
Create Date: 2024-08-15 19:42:37.614539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95bfe20087ce'
down_revision = 'f6f74ec74b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint('rewards_ibfk_2', type_='foreignkey')
        batch_op.drop_column('donation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('rewards_ibfk_2', 'donations', ['donation_id'], ['id'])

    # ### end Alembic commands ###
