"""Add recurring, anonymous, and gift_aid fields to Donation model

Revision ID: 99ae9d24f07c
Revises: 39fa40510dc0
Create Date: 2024-11-04 11:05:18.274143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ae9d24f07c'
down_revision = '39fa40510dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gift_aid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('gift_aid')
        batch_op.drop_column('anonymous')
        batch_op.drop_column('recurring')

    # ### end Alembic commands ###
