"""Update payment model with new fields

Revision ID: aab9ed4c700f
Revises: d3f1e248bef1
Create Date: 2024-10-25 12:49:26.155181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab9ed4c700f'
down_revision = 'd3f1e248bef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.Enum('STRIPE', 'PAYPAL', 'SQUARE', 'RAZORPAY', 'FLUTTERWAVE', name='paymentprovider'), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('payment_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_metadata')
        batch_op.drop_column('error_message')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
