"""Add idempotency_key to donations and payments

Revision ID: bd5b8b911a61
Revises: 99ae9d24f07c
Create Date: 2024-11-05 16:32:19.501508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5b8b911a61'
down_revision = '99ae9d24f07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_donation_idempotency', ['user_id', 'project_id', 'amount', 'idempotency_key'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_donation_idempotency', type_='unique')
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
