"""Add minimum_amount to rewards table

Revision ID: d3f1e248bef1
Revises: fac702e6aae5
Create Date: 2024-10-23 08:22:57.545059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f1e248bef1'
down_revision = 'fac702e6aae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_column('minimum_amount')

    # ### end Alembic commands ###
