"""Add rewards relationship to Project

Revision ID: f6f74ec74b82
Revises: 76420b9375ea
Create Date: 2024-08-15 12:16:43.748932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f74ec74b82'
down_revision = '76420b9375ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rewards', ['reward_id'], ['id'])

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'donations', ['donation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('donation_id')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reward_id')

    # ### end Alembic commands ###
