"""Update reward model with new fields

Revision ID: fac702e6aae5
Revises: 2ff8bdc57074
Create Date: 2024-10-23 02:18:07.372662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fac702e6aae5'
down_revision = '2ff8bdc57074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimed_rewards',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipping_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('minimum_amount')
        batch_op.drop_column('estimated_delivery')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('minimum_amount', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('shipping_type')
        batch_op.drop_column('estimated_delivery_date')

    op.drop_table('claimed_rewards')
    # ### end Alembic commands ###
